pub enum Command {
    Lock,
    List,
    Info,
    Help,
    Exit,
    Commit,
    Clear,
    Passwd,
    Get(String),
    Unlock(String),
    Create(String),
    Remove(String),
    Rename(String),
    Copy(String),
    Export(String),
    Import(String),
    Update(String),
    Drop(String),
    Gen(Option<usize>),
    Add { service: String, username: String },
}
